
import './globals.css';




import { Inter } from 'next/font/google'
import Providers from './redux/provider';


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Fastfood express order online food',
  description: 'Generated by create next app',
}
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'G-WK4TS2TJD5');
export default function RootLayout({ children }) {
  return (
    <html style={{scrollBehavior:"smooth"}} lang="en">
      <head>
      
<script async src="https://www.googletagmanager.com/gtag/js?id=G-WK4TS2TJD5"></script>

  

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@500&family=Hind+Siliguri&family=Roboto:wght@400;500&family=Ubuntu&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

        <link rel="preload" as='font' href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0+display=swap" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@40,300,0,-25" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Gabarito:wght@600&family=Poppins&display=swap" rel="stylesheet" />

        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
<link href="https://fonts.googleapis.com/css2?family=Cabin:wght@600&family=Gabarito:wght@600&family=Poppins&display=swap" rel="stylesheet"></link>


<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@24,200,0,-25" />

      </head>
      <body className={inter.className}>

        <Providers>
          {children}
        </Providers>


      </body>
    </html>
  )
}
